import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


import AuthProvider from "@/context/authContext";
import { ThemeProvider } from "@/context/themeContext";
import ChildRootLayout from "@/components/childLayouts/ChildRootLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            <ChildRootLayout>
              {children}
            </ChildRootLayout>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
